// Generates the full item catalog from the Kenney CC0 pack.
// - copies every real sprite into public/assets/pack/<id>.png
// - writes public/js/shared/pack-items.js  (PACK_ITEMS)
//
// Run:  node tools/genpack.mjs
import fs from 'fs';
import path from 'path';
import os from 'os';

const SRC = path.join(os.tmpdir(), 'gt_assets', 'extracted');
const OUT_DIR = path.join('public', 'assets', 'pack');
const OUT_JS = path.join('public', 'js', 'shared', 'pack-items.js');

if (!fs.existsSync(SRC)) { console.error('Extracted pack not found at', SRC); process.exit(1); }
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

const EXP_SHORT = {
  'Base pack': 'Base', 'Buildings expansion': 'Buildings', 'Candy expansion': 'Candy',
  'Ice expansion': 'Ice', 'Mushroom expansion': 'Mushroom', 'Request pack': 'Request',
  'Extra animations and enemies': 'Extra',
};
// core gameplay items already own these source files — skip to avoid duplicates
const CORE_SRC = new Set([
  'dirtCenter', 'grassMid', 'stoneCenter', 'sandCenter', 'brickWall', 'window',
  'liquidLava', 'box', 'grassCenter', 'stoneWall', 'sign', 'lock_blue', 'lock_yellow',
  'lock_red', 'gemBlue', 'plant',
]);
const NON_SOLID_TILE = /(liquid|water|lava|door|ladder|sign|torch|toch|rope|chain|window|fence|spike|lock|bridgeLogs|peg)/i;

function walk(dir, files = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, files);
    else if (e.name.toLowerCase().endsWith('.png')) files.push(full);
  }
  return files;
}

function titleCase(id) {
  return id
    .replace(/[_-]+/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([a-zA-Z])(\d)/g, '$1 $2')
    .replace(/\s+/g, ' ').trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const usedIds = new Set();
function uniqueId(base, relSegs) {
  let id = base;
  if (usedIds.has(id)) {
    const hint = relSegs.find((s) => /tiles|items|enemies|hud|object|tile/i.test(s)) || relSegs[relSegs.length - 2] || '';
    id = (hint ? hint.replace(/[^a-z0-9]/gi, '') + '_' : '') + base;
    let n = 2;
    while (usedIds.has(id)) id = base + '_' + (n++);
  }
  usedIds.add(id);
  return id;
}

const all = walk(SRC);
const items = {};
let copied = 0;

for (const full of all) {
  const rel = path.relative(SRC, full);
  const segs = rel.split(path.sep);
  const file = segs[segs.length - 1];
  const base = file.replace(/\.png$/i, '');

  // ---- exclusions ----
  if (/_spritesheet$/i.test(base)) continue;        // atlases
  if (/^(preview|sample|bg|bg_castle)$/i.test(base)) continue;
  if (/^bg($|_)/i.test(base)) continue;
  if (segs.includes('Player')) continue;            // the avatar's own frames
  if (segs.includes('Vector')) continue;
  if (CORE_SRC.has(base)) continue;

  const expansion = EXP_SHORT[segs[0]] || segs[0];
  const sub = segs.length >= 3 ? segs[1] : 'Misc';
  const inTiles = segs.some((s) => /^tiles?$/i.test(s));
  const solid = inTiles && !NON_SOLID_TILE.test(base);
  const hazard = /lava/i.test(base) ? 'lava' : (/spike/i.test(base) ? 'spike' : undefined);

  let hardness;
  if (solid) {
    if (/stone|castle|rock|metal|brick|block|box|iron|steel/i.test(base)) hardness = 7;
    else if (/sand|snow|ice|dirt|cake|candy|jelly|mushroom|slime/i.test(base)) hardness = 4;
    else hardness = 5;
  } else hardness = 2;

  const id = uniqueId(base, segs);
  fs.copyFileSync(full, path.join(OUT_DIR, id + '.png'));
  copied++;

  const def = {
    id,
    name: titleCase(base),
    type: solid ? 'block' : 'special',
    solid,
    hardness,
    price: solid ? hardness * 6 : 14,
    category: `${expansion} · ${sub}`,
    sprite: `assets/pack/${id}.png`,
    drops: { block: id, gemMin: 0, gemMax: solid ? 1 : 0 },
  };
  if (hazard) def.hazard = hazard;
  items[id] = def;
}

// stable, readable output
const keys = Object.keys(items).sort();
let out = '// AUTO-GENERATED by tools/genpack.mjs — do not edit by hand.\n';
out += '// Every sprite from the Kenney "Platformer Art Complete Pack" (CC0) as a game item.\n';
out += 'export const PACK_ITEMS = {\n';
for (const k of keys) out += '  ' + JSON.stringify(k) + ': ' + JSON.stringify(items[k]) + ',\n';
out += '};\n';
fs.writeFileSync(OUT_JS, out);

// category summary
const cats = {};
for (const k of keys) cats[items[k].category] = (cats[items[k].category] || 0) + 1;
console.log(`Copied ${copied} sprites -> ${OUT_DIR}`);
console.log(`Wrote ${keys.length} items -> ${OUT_JS}`);
console.log('Categories:');
for (const c of Object.keys(cats).sort()) console.log('  ' + c.padEnd(26) + cats[c]);
